const adjectives = ['abandoned','able','absolute','adorable','adventurous','agile','amazing','ambitious','ancient','angry','animated','aquatic','arctic','awesome','balanced','beautiful','blazing','bold','brave','breezy','bright','brilliant','calm','celestial','charming','cheerful','clever','coastal','colorful','cosmic','cozy','creative','crimson','crystal','curious','daring','dazzling','deep','delicate','divine','dreamy','dynamic','eager','early','eastern','electric','elegant','emerald','enchanted','endless','energetic','epic','eternal','exotic','fabulous','fancy','fantastic','fast','fearless','fierce','fiery','flaming','flying','focused','forest','free','fresh','friendly','frozen','future','gentle','giant','glorious','golden','graceful','grand','great','green','happy','harmonic','hidden','holy','humble','icy','infinite','inner','jade','jolly','joyful','keen','kind','lasting','legendary','light','lively','lone','lost','lovely','lucky','lunar','magic','majestic','marble','mellow','mighty','misty','modern','moonlit','morning','mountain','mystic','natural','nimble','noble','northern','ocean','olive','orange','outer','peaceful','perfect','phantom','pink','pleasant','polar','polished','powerful','precious','prime','proud','purple','quick','quiet','radiant','rapid','rare','red','regal','resilient','rising','robust','rocky','royal','ruby','rustic','sacred','sandy','sapphire','scarlet','secret','serene','shadow','shiny','silent','silver','simple','sleek','smooth','snowy','soft','solar','solid','southern','sparkling','special','spiral','spring','starry','steady','stellar','still','stormy','strong','summer','sunny','super','swift','tender','thunder','tidal','tiny','tranquil','tropical','true','twilight','ultra','unique','vast','velvet','vibrant','violet','vivid','wandering','warm','western','white','wild','winter','wise','wonderful','young','zealous'];

const nouns = ['account','action','air','anchor','angel','apple','arrow','aurora','autumn','badge','ball','beacon','bear','bird','blade','bloom','bolt','book','breeze','bridge','brook','canyon','castle','cave','cedar','cherry','cliff','cloud','coast','comet','coral','cosmos','cove','crane','creek','crest','crown','crystal','dawn','desert','diamond','dolphin','dove','dragon','dream','dune','eagle','earth','echo','edge','ember','falcon','feather','field','fire','flame','flash','flower','fog','forest','fountain','fox','frost','galaxy','garden','gate','gem','glacier','glade','glow','grove','harbor','hawk','heart','hill','horizon','island','jade','jewel','jungle','lake','leaf','light','lion','lotus','maple','marble','meadow','meteor','mist','moon','moss','mountain','nebula','nest','night','oak','oasis','ocean','orchid','owl','palm','panther','path','peak','pearl','phoenix','pine','planet','pond','prairie','prism','rain','rainbow','raven','reef','ridge','river','rock','rose','ruby','sage','sand','sapphire','sea','shadow','shore','sky','snow','spark','spring','star','stone','storm','stream','summit','sun','sunset','swan','temple','thunder','tide','tiger','trail','tree','tulip','valley','vine','violet','vista','void','wave','willow','wind','wing','winter','wolf','wood','zenith'];

export const generatePhaseName = () => {
  const adj = adjectives[Math.floor(Math.random() * adjectives.length)];
  const noun = nouns[Math.floor(Math.random() * nouns.length)];
  return `${adj.charAt(0).toUpperCase() + adj.slice(1)} ${noun.charAt(0).toUpperCase() + noun.slice(1)}`;
};
